### PR TITLE
Fix unmarshal/validate of binary type leaf value

### LINKED ISSUE #293: Failing to unmarshal Binary type & validation also broken
Currently ygot fails on unmarshaling binary type leafs due to assuming `[]byte` rather than derived type `Binary`.

Also, even if the unmarshaling is fixed, the validation is similarly broken for binary type.

### Example Data

The following is a basic YANG model to exhibit this:
```yang
module a {
  prefix a;
  namespace "urn:a";
  revision 2019-07-06 {
    description "Initial";
  }

  container top {
    leaf test {
      type binary {
        length 2;
      }
    }
  }
}
```

Using a sample JSON encoded data of:
```json
{
  "a:top": {
    "test": "NDI="
  }
}
```

### Unmarshal issue

Unmarshal currently fails with: **cannot assign value [52 50] (type []uint8) to struct field Test (type a.Binary) in struct \*a.A_Top**

The problem is in `reflect.InsertIntoStruct`.
Since `Binary` is derived type, a cast similar to `YANGEmpty` is required.

### Validation issue

Validate currently passes no matter the input length of binary data. For example, changing the value to JSON binary input to `"NDIgNDIgNDIgNDIgNDI="` will still pass.

The first problem here is in `validateLeaf` of leaf.go. The `rv` value passed to `return util.NewErrs(validateBinary(schema, rv))` is `nil` since there it is never set.

The second problem is `validateBinary` of `binary_type.go`. Here, the data is processed as if it was the base type `[]byte` rather than the derived type `Binary`.

### Other changes required

Various tests need to be changed to use some variant of `Binary` as they are incorrectly passing.

### PR DESCRIPTION
**Pull request by cho-m**
Fixes #293 

Also adds a few other tests for some code that wasn't covered.

### CODE REVIEW

File: util/reflect.go [hunk 1]
```diff
@@ -266,6 +266,14 @@ func InsertIntoStruct(parentStruct interface{}, fieldName string, fieldValue int
 		v = nv
 	}
 
+	// YANG binary fields are represented as a derived []byte value defined in the
+	// generated code. Here we cast the value to the type in the generated code.
+	if ft.Type.Kind() == reflect.Slice && t.Kind() == reflect.Slice && ft.Type.Elem().Kind() == reflect.Uint8 && t.Elem().Kind() == reflect.Uint8 {
```
Comment (robshakir) [inline util/reflect.go]: It's worth adding a comment here that this will actually trigger for slices of `uint8` -- i.e., `leaf-list` nodes of type `uint8`. We can safely treat the two as the same though since `[]byte` and `[]uint8` are equivalent in the underlying implementation (see https://play.golang.org/p/hpD9IeYY9hH for a quick check that `SetBytes` won't panic).

File: util/reflect_test.go [hunk 2]
```diff
@@ -568,6 +582,62 @@ func TestIsValueTypeComaptible(t *testing.T) {
...
+	}
+
+	tests := []struct {
+		desc         string
+		parentStruct interface{}
+		fieldName    string
+		fieldValue   interface{}
+		wantVal      interface{}
+		wantErr      string
+	}{
```
Comment (robshakir) [inline util/reflect_test.go]: Can we add a test here that covers the `[]uint8` case that I mentioned above? Thanks for adding this coverage!

File: ytypes/binary_type.go [hunk 3]
```diff
@@ -35,12 +37,13 @@ func validateBinary(schema *yang.Entry, value interface{}) error {
 	}
 
 	// Check that type of value is the type expected from the schema.
-	binaryVal, ok := value.([]byte)
-	if !ok {
+	t := reflect.TypeOf(value)
```
Comment (robshakir) [inline ytypes/binary_type.go]: We should probably create a helper here -- `isBinaryField(reflect.Type)` and re-write this:

```golang
if t := reflect.TypeOf(value); !isBinaryType(t) { ...
```

Since we use the same logic below.

File: ytypes/binary_type.go [hunk 4]
```diff
@@ -58,21 +61,24 @@ func validateBinarySlice(schema *yang.Entry, value interface{}) error {
...
+	tbl := make(map[string]bool, v.Len())
+	for i := 0; i < v.Len(); i++ {
+		val := v.Index(i)
+		if err := validateBinary(schema, val.Interface()); err != nil {
 			return fmt.Errorf("invalid element at index %d: %v", i, err)
 		}
-		if tbl[string(val)] {
-			return fmt.Errorf("duplicate binary type: %v for schema %s", val, schema.Name)
+		binaryVal := val.Bytes()
+		if tbl[string(binaryVal)] {
```
Comment (robshakir) [inline ytypes/binary_type.go]:
```golang
if tbl[string(val.Bytes())] { ...
```

File: util/reflect.go (hunk 1 above)
Comment (cho-m) [reply util/reflect.go]: Added comment for `[]uint8` behavior

File: util/reflect_test.go (hunk 2 above)
Comment (cho-m) [reply util/reflect_test.go]: Added test case for corresponding scenario.

File: ytypes/binary_type.go (hunk 3 above)
Comment (cho-m) [reply ytypes/binary_type.go]: Refactored logic to dedicated functions for:
* `isBinaryType` - to do type test previously handled by `.([]byte)`
* `isBinarySliceType` - to do type test previously handled by `.([][]byte)`

File: ytypes/binary_type.go (hunk 4 above)
Comment (cho-m) [reply ytypes/binary_type.go]: I had done assignment to `binaryVal` since there is a few more lines of logic that use the value.
Let me know if the preference would be to just use `val.Bytes()` in the corresponding locations.

Comment (robshakir) [reply ytypes/binary_type.go]: Ah, sorry, missed that you used it again. LGTM.

File: util/reflect.go (hunk 1 above)
Comment (robshakir) [reply util/reflect.go]: Great, thanks.

File: util/reflect_test.go (hunk 2 above)
Comment (robshakir) [reply util/reflect_test.go]: Perfect, thanks.
