### PR TITLE
Fix genenerator's flag descriptions

### LINKED ISSUE #768: Generator options and `structs_split_files_count`
👋 all,
I see that in the generator flags we mention that `structs_split_files_count` works only when `output_file` is specified.

https://github.com/openconfig/ygot/blob/faf395436e2fae19420fa3638114ddfb1909bea5/generator/generator.go#L58

But I think the description is false, because we actually need to not use `output_file` and use `output_dir` instead.

If you agree with that, I can file a PR with fixing the flag description.

### PR DESCRIPTION
**Pull request by n0shut**
fix #768 

Hi @wenovus, does this match what you suggested in #768

### CODE REVIEW

File: generator/generator.go [hunk 1]
```diff
@@ -55,9 +55,9 @@ var (
...
 	ocStructsOutputFile     = flag.String("output_file", "", "The file that the generated Go code for manipulating YANG data (schema/Go structs) should be written to. Specify \"-\" for stdout.")
-	structsFileN            = flag.Int("structs_split_files_count", 0, "The number of files to split the generated schema structs into when output_file is specified.")
+	structsFileN            = flag.Int("structs_split_files_count", 0, "The number of files to split the generated schema structs into when output_dir is specified.")
 	ocPathStructsOutputFile = flag.String("path_structs_output_file", "", "The file that the generated Go code for YANG path construction (path structs) will be generated. If split_pathstructs_by_module=true, this file contains the fake root path struct. Specify \"-\" for stdout.")
-	pathStructsFileN        = flag.Int("path_structs_split_files_count", 0, "The number of files to split the generated path structs into when output_file is specified for generating path structs")
+	pathStructsFileN        = flag.Int("path_structs_split_files_count", 0, "The number of files to split the generated path structs into when output_dir is specified for generating path structs")
```
Comment (wenovus) [inline generator/generator.go:60]:
```suggestion
	pathStructsFileN        = flag.Int("path_structs_split_files_count", 0, "The number of files to split the generated path structs into when output_dir or split_pathstructs_by_module is specified for generating path structs")
```

**Review by wenovus — CHANGES_REQUESTED** [review]
Yep, almost, just wanted to add one more

**Comment by n0shut** [comment]
thanks @wenovus!

**Review by wenovus — APPROVED** [review]
